/*==============================================================*/
/* CRÉATION DES SYNONYMES PUBLICS (Alias)                       */
/*==============================================================*/
-- Cela permet à BANK_APP_USER de voir les tables comme si c'étaient les siennes.
-- Remplacez "SYSTEM" par le nom du créateur des tables si ce n'est pas SYSTEM.

-- 1. TABLES
CREATE OR REPLACE PUBLIC SYNONYM AGENCE FOR SYSTEM.AGENCE;
CREATE OR REPLACE PUBLIC SYNONYM CLIENT FOR SYSTEM.CLIENT;
CREATE OR REPLACE PUBLIC SYNONYM COMPTE FOR SYSTEM.COMPTE;
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYE FOR SYSTEM.EMPLOYE;
CREATE OR REPLACE PUBLIC SYNONYM PRET FOR SYSTEM.PRET;
CREATE OR REPLACE PUBLIC SYNONYM REMBOURSEMENT FOR SYSTEM.REMBOURSEMENT;
CREATE OR REPLACE PUBLIC SYNONYM TRANSACTIONS FOR SYSTEM.TRANSACTIONS;
CREATE OR REPLACE PUBLIC SYNONYM HISTORIQUE_SALAIRE FOR SYSTEM.HISTORIQUE_SALAIRE;

-- 2. SÉQUENCES
CREATE OR REPLACE PUBLIC SYNONYM AGENCE_SEQ FOR SYSTEM.AGENCE_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM CLIENT_SEQ FOR SYSTEM.CLIENT_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM TRANSACTIONS_SEQ FOR SYSTEM.TRANSACTIONS_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM PRET_SEQ FOR SYSTEM.PRET_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM REMBOURSEMENT_SEQ FOR SYSTEM.REMBOURSEMENT_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM HISTORIQUE_SALAIRE_SEQ FOR SYSTEM.HISTORIQUE_SALAIRE_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYE_SEQ FOR SYSTEM.EMPLOYE_SEQ;

-- 3. PROCÉDURES ET FONCTIONS
CREATE OR REPLACE PUBLIC SYNONYM DEPOT FOR SYSTEM.DEPOT;
CREATE OR REPLACE PUBLIC SYNONYM RETRAIT FOR SYSTEM.RETRAIT;
CREATE OR REPLACE PUBLIC SYNONYM TRANSFERT FOR SYSTEM.TRANSFERT;
CREATE OR REPLACE PUBLIC SYNONYM DEMANDER_PRET FOR SYSTEM.DEMANDER_PRET;
CREATE OR REPLACE PUBLIC SYNONYM VALIDER_PRET FOR SYSTEM.VALIDER_PRET;
CREATE OR REPLACE PUBLIC SYNONYM AJOUTER_AGENCE FOR SYSTEM.AJOUTER_AGENCE;
CREATE OR REPLACE PUBLIC SYNONYM MODIFIER_AGENCE FOR SYSTEM.MODIFIER_AGENCE;
CREATE OR REPLACE PUBLIC SYNONYM P_RECRUTER_EMPLOYE FOR SYSTEM.P_RECRUTER_EMPLOYE;
CREATE OR REPLACE PUBLIC SYNONYM P_CHANGER_AFFECTATION FOR SYSTEM.P_CHANGER_AFFECTATION;
CREATE OR REPLACE PUBLIC SYNONYM P_AUGMENTER_SALAIRE FOR SYSTEM.P_AUGMENTER_SALAIRE;
CREATE OR REPLACE PUBLIC SYNONYM P_LICENCIER_EMPLOYE FOR SYSTEM.P_LICENCIER_EMPLOYE;
CREATE OR REPLACE PUBLIC SYNONYM P_VALIDER_COMPTE FOR SYSTEM.P_VALIDER_COMPTE;
CREATE OR REPLACE PUBLIC SYNONYM F_GET_NOM_MANAGER FOR SYSTEM.F_GET_NOM_MANAGER;
CREATE OR REPLACE PUBLIC SYNONYM F_CALCULER_ANCIENNETE FOR SYSTEM.F_CALCULER_ANCIENNETE;
CREATE OR REPLACE PUBLIC SYNONYM F_SALAIRE_TOTAL_AGENCE FOR SYSTEM.F_SALAIRE_TOTAL_AGENCE;